import {
  Alert,
  Box,
  Chip,
  Divider,
  Paper,
  Stack,
  Typography,
} from "@mui/material";

import PsychologyIcon from "@mui/icons-material/Psychology";
import PersonIcon from "@mui/icons-material/Person";
import WarningAmberIcon from "@mui/icons-material/WarningAmber";
import VerifiedIcon from "@mui/icons-material/Verified";

import type { Investigation } from "../../../../types/investigation";

interface Props {
  investigation: Investigation;
}

export default function IncidentSummaryContent({
  investigation,
}: Props) {
  return (
    <Stack spacing={3}>
      <Paper sx={{ p: 3, borderRadius: 3 }}>
        <Typography variant="h6" gutterBottom>
          Executive Summary
        </Typography>

        {investigation.executive.summary.map((item, index) => (
          <Typography key={index} sx={{ mb: 1 }}>
            • {item}
          </Typography>
        ))}
      </Paper>

      <Paper sx={{ p: 3, borderRadius: 3 }}>
        <Stack direction="row" spacing={2} alignItems="center">
          <WarningAmberIcon color="warning" />

          <Box>
            <Typography variant="subtitle2">
              Likely Root Cause
            </Typography>

            <Typography variant="body1">
              {investigation.executive.likely_cause}
            </Typography>
          </Box>
        </Stack>

        <Divider sx={{ my: 3 }} />

        <Stack direction="row" spacing={2} alignItems="center">
          <PersonIcon color="primary" />

          <Box>
            <Typography variant="subtitle2">
              Recommended Owner
            </Typography>

            <Typography>
              {investigation.executive.recommended_owner}
            </Typography>
          </Box>
        </Stack>
      </Paper>

      <Paper sx={{ p: 3, borderRadius: 3 }}>
        <Stack direction="row" spacing={2} alignItems="center">
          <VerifiedIcon color="success" />

          <Box>
            <Typography variant="subtitle2">
              AI Confidence
            </Typography>

            <Chip
              color="success"
              label={`${investigation.ai_result.confidence}%`}
            />
          </Box>
        </Stack>
      </Paper>

      <Alert
        icon={<PsychologyIcon />}
        severity="info"
      >
        This summary was generated by the AI investigation engine
        using Kubernetes, Deployment, Logs, Metrics, Network,
        Knowledge Base and Correlation analysis.
      </Alert>
    </Stack>
  );
}