"""create incidents table

Revision ID: 72a643570393
Revises: 7b0f183e84f8
Create Date: 2026-07-20 00:22:23.633402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a643570393'
down_revision: Union[str, Sequence[str], None] = '7b0f183e84f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('sys_id', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('assignment_group', sa.String(length=255), nullable=True),
    sa.Column('configuration_item', sa.String(length=255), nullable=True),
    sa.Column('caller', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_number'), 'incidents', ['number'], unique=True)
    op.create_index(op.f('ix_incidents_sys_id'), 'incidents', ['sys_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_sys_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_number'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
