"""create investigations table

Revision ID: 7b0f183e84f8
Revises: 
Create Date: 2026-07-19 00:59:13.705958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b0f183e84f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_number', sa.String(length=50), nullable=False),
    sa.Column('incident_sys_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_incident_number'), 'investigations', ['incident_number'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_incident_number'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
